service: serverless-rust-example

provider:
  name: aws
  runtime: rust
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ec2:DeleteNetworkInterface'
        - 'ec2:DetachNetworkInterface'
        - 'ec2:DescribeNetworkInterfaces'
      Resource: '*'

plugins:
  - serverless-rust
  - serverless-prune-plugin
  - serverless-plugin-vpc-eni-cleanup

package:
  individually: true

custom:
  rust:
    dockerless: true
  prune:
    automatic: true
    number: 3

functions:
  hello:
    handler: serverless-rust-example.hello
    events:
      - http:
          path: /hello
          method: GET
  goodbye:
    handler: serverless-rust-example.goodbye
    events:
      - http:
          path: /goodbye
          method: GET
