name: Rust

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Do you release? (y/n)'
        required: true
        default: 'n'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
